### ISSUE TITLE
M1 support

### ISSUE THREAD

**Issue by karolbisztyga** [surge-synthesizer/monique-monosynth#115]
Does monique support macs with M1? And if not, will the support be added and when? Thank you!

I tried to build it and the build was successful on the mac m1 pro but vst3 still doesn't work in ableton :/

**Comment by ghost** [comment]
Hi. M1 is supported. 
Can you clarify what you mean when you say "doesn't work",
and which version of live you are running?

I know older versions don't support vst3 
but since you're on an m1 I assume you use v11?
Otherwise there is also an AU you can try.

Another thought: Once you built the plugin you still have to
copy it to a vst3 directory that live can see (or point live to the plugin).
Alternatively you can use the installer here: 
https://github.com/surge-synthesizer/monique-monosynth/releases

Does any of this help?

**Comment by karolbisztyga** [comment]
I use Live 11.1.6
All I do is just put `.vst`/`.vst3` files in the directories along with other vsts (so I know the place itself is valid as other VSTs work), thne I reload plugins in Live's settings (also tried resetting Live).

After I built it locally, I did the same routine with the `.vst3` file.

Eventually, the installer from the releasees worked! 🎉  Thank you very much!

**Comment by baconpaul** [comment]
If you built it yourself live may have a problem with the code signature. Our build won’t sign blank by default and live is particular about that. The installer has a fully signed vst3
